// Generated by gencpp from file robot_msgs/HeadStatus.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_HEADSTATUS_H
#define ROBOT_MSGS_MESSAGE_HEADSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct HeadStatus_
{
  typedef HeadStatus_<ContainerAllocator> Type;

  HeadStatus_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  HeadStatus_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;





  typedef boost::shared_ptr< ::robot_msgs::HeadStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::HeadStatus_<ContainerAllocator> const> ConstPtr;

}; // struct HeadStatus_

typedef ::robot_msgs::HeadStatus_<std::allocator<void> > HeadStatus;

typedef boost::shared_ptr< ::robot_msgs::HeadStatus > HeadStatusPtr;
typedef boost::shared_ptr< ::robot_msgs::HeadStatus const> HeadStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::HeadStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::HeadStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_msgs': ['/home/tinker/catkin_ws/src/robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::HeadStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::HeadStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::HeadStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::HeadStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::HeadStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::HeadStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::HeadStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938e11f380abc0513a5b7367d0f157bf";
  }

  static const char* value(const ::robot_msgs::HeadStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938e11f380abc051ULL;
  static const uint64_t static_value2 = 0x3a5b7367d0f157bfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::HeadStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/HeadStatus";
  }

  static const char* value(const ::robot_msgs::HeadStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::HeadStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pan\n\
float32 tilt\n\
";
  }

  static const char* value(const ::robot_msgs::HeadStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::HeadStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::HeadStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::HeadStatus_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_HEADSTATUS_H
